mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

polls/urls.py
# path() takes {route}, {view}, [{kwang}, {name}]
from django.urls import path
from . import views

# set the application namespace
app_name = "polls"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("new/", views.create_poll, name="create_poll"),
    path("delete_polls/", views.delete_polls, name="delete_polls"),
]

polls/models.py
import datetime
from datetime import date
from django.db import models
from django.utils import timezone
from django.contrib import admin

# each model is represented by a class that subclasses django.db.models.Model.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    end_date = models.DateTimeField("due date", blank=True, null=True)
    is_due = models.BooleanField(default=False)

    # save method override
    # args = positional arguments
    # kwargs = key-value pair arguments
    def save(self):
        if not self.end_date:
            self.end_date = date.today() + datetime.timedelta(days=7)
        super().save()

    # for this object's representation
    def __str__(self):
        return self.question_text

    # sort the column header for was_published_recently in admin page
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    # self is for instance method; This allows the method to access the instance's attributes and other methods
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    def is_due(self):
        now = timezone.now()
        if now <= self.end_date:
            self.is_due = True


class Choice(models.Model):
    # to change default related manager name 'choice_set', define 'related_name'
    # question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    is_most_voted = models.BooleanField(default=False)
    def __str__(self):
        return self.choice_text
    @classmethod
    def most_voted(cls, question_id):
        # access the Question's primary key directly via the question_id attribute of the Choice model. This attribute is automatically created by Django for the ForeignKey field
        choices = cls.objects.filter(question_id=question_id)
        if not choices.exists():
            return None
        # the hyphen (-) before a field name in the order_by method indicates descending order
        most_voted_choice = choices.order_by('-votes').first()

        # extracts the votes values from each Choice object in the QuerySet
        votes_list = choices.values_list('votes', flat=True)
        
        # a list comprehension
        filtered_votes = [vote for vote in votes_list if vote == most_voted_choice.votes]

        if len(filtered_votes) == 1:
            choices.update(is_most_voted=False)
            most_voted_choice.is_most_voted = True
            most_voted_choice.save()
        else:
            choices.update(is_most_voted=False)

        

polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

from .models import Choice, Question

"""
Generic views abstract common patterns to the point where you dont even need to write Python code to write an app. For example, the ListView and DetailView generic views abstract the concepts of “display a list of objects” and “display a detail page for a particular type of object”
"""
class IndexView(generic.ListView):
    template_name = "polls/index.html"
    # override the default context_object_name(question_list)
    context_object_name = "latest_question_list"
    # "latest_question_list"
    def get_queryset(self):
        """
        Return the last 6 published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:6]


class DetailView(generic.DetailView):
    # Each generic view needs to know what model it will be acting upon
    model = Question
    # override the default template_name(polls/question_detail.html)
    template_name = "polls/detail.html"
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

# class ResultsView(generic.DetailView):
#     model = Question
#     template_name = "polls/results.html"

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # update is_most_voted field before rendering
    Choice.most_voted(question.id) 
    return render(request, 'polls/results.html', {"question": question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # test the exception to occur
    try:
        # request.POST['choice'] returns the ID of the selected choice
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    # if there is no exception then execute this block     
    else:
        # F("votes") + 1 instructs the database to increase the vote count by 1
        selected_choice.votes = F("votes") + 1
        selected_choice.save()

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        # this reverse() call will return a string like "/polls/3/results/", not "/polls/results/3/"
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

def create_poll(request):
    if request.method == 'POST':
        # request.POST is a dictionary-like object that contains all the data submitted in the form.
        # Each form field's data is retrieved by its name attribute
        question_text = request.POST['question_text']
        pub_date = request.POST['pub_date']
        end_date = request.POST['end_date']
        # how many choices user chose
        num_of_choice = int(request.POST['num_of_choice'])
        
        # Create the Question object
        question = Question(question_text=question_text, pub_date=pub_date, end_date=end_date)
        question.save()
        
        # Create Choice objects
        # question.choice_set.create(choice_text=choice_1) creates and saves a Choice object
        # choice_set is a related manager provided by Django for reverse relations (from Question to Choice).
        # By default, the related manager is named <model>_set

        # create as many choices as user chose 
        for i in range(1, num_of_choice + 1):
            choice_text = request.POST[f'choice_{i}']
            if choice_text:
                question.choice_set.create(choice_text=choice_text)
        
        # redirect to index page
        return redirect('polls:index')
    
    # If the request method is not POST (typically a GET request), this line renders the form template.
    # return render(request, 'polls/create_poll.html', 
    # {'num_of_choice': int(request.POST['num_of_choice'])+1})
    return render(request, 'polls/create_poll.html')

def delete_polls(request):
    print("Request received: ", request.method)
    if request.method == 'POST':
        poll_ids_string = request.POST['poll_ids'] # string value
        poll_ids = [int(num) for num in poll_ids_string.split(',')]

        for id in poll_ids:
            Question.objects.filter(id=id).delete()

    return redirect('polls:index')
    

polls/templates/polls/create_poll.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<div class="container m-3 p-3">
    <!-- it will generate url pattern localhost:8000/polls/new -->
    <form action="{% url 'polls:create_poll' %}" method="post">
        {% csrf_token %}
        <legend><h1>Create a new poll</h1></legend>
        <div class="mb-3">
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Poll Question</label>
            <input type="text" class="form-control" id="question_text" name="question_text" required>
        </div>
        <div class="mb-3">         
            <div class="row">
                <div class="col">
                    <label for="" class="form-label">Publish Date</label>
                    <input type="date" class="form-control" id="pub_date" name="pub_date" required>
                    <div id="pub_date_help" class="form-text">The question which publish date in the future won't be displayed until the date.</div>
                </div>
                <div class="col">
                    <label for="" class="form-label">Set End Date</label>
                    <input type="date" class="form-control" id="end_date" name="end_date">
                    <div id="end_date_help" class="form-text">The default is 7 days from the publish date.</div>
                </div>
            </div>            
        </div>
        <div class="mb-3">
            <div class="row">
                <div class="col">
                    <label for="" class="form-label">How many poll choices do you want?</label>
                </div>
                <div class="col d-flex">
                    <input type="number" class="form-control" id="num_of_choice" name="num_of_choice" required>
                    <button class="btn btn-outline-primary mx-2" type="button" onclick="generateChoices()">Set</button>
                </div>
            </div>  
        </div>
        <div class="mb-3">
            <label for="choices_list" class="form-label">Poll choices</label>
            <ol class="list-group" id="choices_list">
                <!-- List items will be generated here -->
            </ol>
        </div>
        <button class="btn btn-primary" type="submit">Save</button>
        <a href="{% url 'polls:index' %}">
            <button class="btn btn-secondary" type="button">Cancel</button>
        </a>      
    </form>
</div>

<script>
    function generateChoices() {
        let num_of_choice = document.getElementById('num_of_choice').value;
        let choices_list = document.getElementById('choices_list');
        //clear any existing list items
        choices_list.innerHTML = '';
        for (let i = 1; i <= num_of_choice; i++) {
            let li = document.createElement('li');
            li.className = 'list-group-item';
            let input = document.createElement('input');
            input.className = 'form-control'
            input.type = 'text'
            input.id = 'choice_' + i;
            input.name = 'choice_' + i;
            input.placeholder = 'Enter choice ' + i;

            li.appendChild(input);
            choices_list.appendChild(li);
        }
    }
</script>

polls/templates/polls/detail.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<div class="container m-3 p-3">
    <!-- When the form is rendered in the browser, Django will replace {% url 'polls:vote' question.id %} with the actual URL for the vote view, including the question.id as part of the URL -->
    <div class="card-body">
        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            <h3 class="card-title">{{ question.question_text }}</h3>
            <div class="mb-3">
                This vote is closed on {{ question.end_date }}
            </div>
            <div class="mb-3">
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                {% for choice in question.choice_set.all %}
                    <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
            </div>
            <button class="btn btn-info" type="button">Share it</button>
            <button class="btn btn-primary" type="submit" value="Vote">Vote</button>
            <!-- get around inside the site -->
            <a href="{% url 'polls:index' %}" class="btn btn-secondary">Back</a>
        </form>
    </div>
</div>

polls/templates/polls/index.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!--This loads Django's timezone template tags, which we'll need for date operations.-->
{% load tz %}

<div class="container m-3 p-3">
    <form id="deletePollsForm" action="{% url 'polls:delete_polls' %}" method="post">
        {% csrf_token %} <!-- must have inside the form -->
        <div class="row d-flex align-items-start mb-3">
            <div class="col"><h1>Open Polls</h1></div>
            <div class="col">
                <a href="{% url 'polls:create_poll' %}" class="btn btn-success">Add a new Poll</a>
                <button class="btn btn-danger" id="delete_polls_button" onclick="deletePolls()">Delete Polls</button>
            </div>
        </div>
        <input type="hidden" id="poll_ids" name="poll_ids" value="">
    </form>
    {% if latest_question_list %}
    {% for question in latest_question_list %}
    <!--This gets the current date in the format "YYYY-MM-DD" and stores it in a variable-->
    {% now "Y-m-d" as current_date %}
    <!--This creates a temporary variable end_date with the question.end_date formatted as "YYYY-MM-DD"-->
    {% with end_date=question.end_date|date:"Y-m-d" %}
    {% if end_date < current_date %}
    <div class="row my-2" id="poll-{{question.id}}">
        <div class="col">
            <input class="form-check-input mx-2" type="checkbox" name="selected_poll" id="{{question.id}}">
            <span>{{ question.question_text }}</span>
        </div>
        <div class="col-4">
            <button type="button" class="btn btn-outline-success btn-sm">Closed</button>
            <a href="{% url 'polls:results' question.id %}" class="btn btn-info btn-sm">Result</a>
        </div>
    </div>
    {% else %}
    <div class="row my-2" id="poll-{{question.id}}">
        <div class="col">
            <input class="form-check-input mx-2" type="checkbox" name="selected_poll" id="{{question.id}}"> 
            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
        </div>
        <div class="col-4">
            <a href="{% url 'polls:detail' question.id %}" class="btn btn-outline-secondary btn-sm">On-going</a>
        </div>
    </div>
    {% endif %}
    {% endwith %}
    {% endfor %}
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</div>

<script>
    function deletePolls() {
        // checked items
        const selectedPolls = document.querySelectorAll('input[name="selected_poll"]:checked');
        // extract question.id only 
        const pollsIds = Array.from(selectedPolls).map(poll => poll.id)

        if (pollsIds.length > 0) {
            // remove from screen 
            pollsIds.forEach(id => {
            document.getElementById(`poll-${id}`).remove();
            })
            // send value to views.py: POST extracted question_id 
            document.getElementById('poll_ids').value = pollsIds;
            document.getElementById('deletePollsForm').submit();
        }
    }
</script>

polls/templates/polls/results.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<div class="container m-3 p-3">
    <h1>Thank you for voting!</h1>
    <div class="card-body">
        <h3 class="card-title">{{ question.question_text }}</h3>
        {% for choice in question.choice_set.all %}
        <div class="row m-3">
            <div class="col">{{ choice.choice_text }}</div>
            <div class="col">{{ choice.votes }} vote{{ choice.votes|pluralize }}
                {% if choice.is_most_voted %}
                <span style="font-size: 0.6rem; color: white;" class="bg-success p-1">most voted</span>
                {% endif %}
            </div>         
        </div>
        {% endfor %}
        <a href="{% url 'polls:index' %}" class="btn btn-secondary">Back</a>
    </div>
    
</div>